# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-11 10:01
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Community',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_type', models.CharField(choices=[('PU', 'Public'), ('PR', 'Private')], default='PU', max_length=2)),
                ('address', models.CharField(max_length=250)),
                ('coordinates', models.CharField(max_length=250)),
                ('password', models.CharField(max_length=250)),
                ('welcome_message', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Communities',
            },
        ),
        migrations.CreateModel(
            name='CommunityMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_type', models.CharField(choices=[('I', 'Info'), ('W', 'Warning')], default='I', max_length=1)),
                ('date_published', models.DateTimeField(auto_now_add=True)),
                ('message_text', models.TextField()),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auzonetweb.Community')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posted_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('detail', models.TextField()),
                ('date_published', models.DateTimeField(auto_now_add=True)),
                ('scope', models.CharField(choices=[('COM', 'Community'), ('CIT', 'City'), ('PRO', 'Province')], default='COM', max_length=3)),
                ('status', models.CharField(choices=[('A', 'Active'), ('F', 'Finished')], default='A', max_length=1)),
                ('price', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('image', models.ImageField(blank=True, upload_to='uploads/offers/%Y/%m/%d/')),
                ('attended_by', models.ManyToManyField(blank=True, related_name='offer_attended_by', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auzonetweb.Category')),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auzonetweb.Community')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offered_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PublicUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birthdate', models.DateField(null=True)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=1)),
                ('karma', models.IntegerField(default=0)),
                ('avatar', models.ImageField(upload_to='uploads/avatars/%Y/%m/%d/')),
                ('communities', models.ManyToManyField(to='auzonetweb.Community')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('detail', models.TextField()),
                ('date_published', models.DateTimeField(auto_now_add=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('scope', models.CharField(choices=[('COM', 'Community'), ('CIT', 'City'), ('PRO', 'Province')], default='COM', max_length=3)),
                ('status', models.CharField(choices=[('A', 'Active'), ('F', 'Finished')], default='A', max_length=1)),
                ('reward', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('image', models.ImageField(blank=True, upload_to='uploads/requests/%Y/%m/%d/')),
                ('attended_by', models.ManyToManyField(blank=True, related_name='request_attended_by', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auzonetweb.Category')),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auzonetweb.Community')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requested_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
