# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-08 08:57
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Community',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_type', models.CharField(choices=[('PU', 'Public'), ('PR', 'Private')], default='PU', max_length=2)),
                ('address', models.CharField(max_length=250)),
                ('coordinates', models.CharField(max_length=250)),
                ('password', models.CharField(blank=True, max_length=250)),
                ('welcome_message', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Communities',
            },
        ),
        migrations.CreateModel(
            name='CommunityMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_type', models.CharField(choices=[('I', 'Info'), ('W', 'Warning')], default='I', max_length=1)),
                ('date_published', models.DateTimeField(auto_now_add=True)),
                ('message_text', models.TextField()),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auzonetweb.Community')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posted_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('detail', models.TextField()),
                ('date_published', models.DateTimeField(auto_now_add=True)),
                ('scope', models.CharField(choices=[('COM', 'Community'), ('CIT', 'City'), ('PRO', 'Province')], default='COM', max_length=3)),
                ('status', models.CharField(choices=[('A', 'Active'), ('P', 'Pending'), ('F', 'Finished')], default='A', max_length=1)),
                ('price', models.DecimalField(blank=True, decimal_places=2, default=0, help_text='EUR. Leave it blank for no price.', max_digits=10, null=True)),
                ('image', models.ImageField(blank=True, upload_to='uploads/offers/%Y/%m/%d/')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auzonetweb.Category')),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auzonetweb.Community')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offered_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_type', models.CharField(choices=[('O', 'Offer'), ('R', 'Request')], max_length=1)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('owner_voted', models.BooleanField(default=False)),
                ('client_voted', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('A', 'Active'), ('P', 'Pending'), ('F', 'Finished')], default='A', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='PublicUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birthdate', models.DateField(null=True)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=1)),
                ('karma', models.IntegerField(default=0)),
                ('avatar', models.ImageField(upload_to='uploads/avatars/%Y/%m/%d/')),
                ('communities', models.ManyToManyField(to='auzonetweb.Community')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('detail', models.TextField()),
                ('date_published', models.DateTimeField(auto_now_add=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('scope', models.CharField(choices=[('COM', 'Community'), ('CIT', 'City'), ('PRO', 'Province')], default='COM', max_length=3)),
                ('status', models.CharField(choices=[('A', 'Active'), ('P', 'Pending'), ('F', 'Finished')], default='A', max_length=1)),
                ('reward', models.DecimalField(blank=True, decimal_places=2, default=0, help_text='EUR. Leave it blank for no reward.', max_digits=10, null=True)),
                ('image', models.ImageField(blank=True, upload_to='uploads/requests/%Y/%m/%d/')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auzonetweb.Category')),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auzonetweb.Community')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requested_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='auzonetrequest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auzonetweb.Request'),
        ),
        migrations.AddField(
            model_name='order',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='order',
            name='offer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auzonetweb.Offer'),
        ),
        migrations.AddField(
            model_name='order',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='server', to=settings.AUTH_USER_MODEL),
        ),
    ]
