# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-17 11:35
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auzonetweb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_type', models.CharField(choices=[('O', 'Offer'), ('R', 'Request')], max_length=1)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('A', 'Active'), ('F', 'Finished')], default='A', max_length=1)),
            ],
        ),
        migrations.RemoveField(
            model_name='offer',
            name='attended_by',
        ),
        migrations.RemoveField(
            model_name='request',
            name='attended_by',
        ),
        migrations.AlterField(
            model_name='community',
            name='password',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='order',
            name='offer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auzonetweb.Offer'),
        ),
        migrations.AddField(
            model_name='order',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='order',
            name='request',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auzonetweb.Request'),
        ),
        migrations.AddField(
            model_name='publicuser',
            name='orders',
            field=models.ManyToManyField(to='auzonetweb.Order'),
        ),
    ]
