# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-02 08:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auzonetweb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='access_type',
            field=models.CharField(choices=[('PU', 'Public'), ('PR', 'Private')], default='PU', help_text='You can protect with password the community access.', max_length=2),
        ),
        migrations.AlterField(
            model_name='community',
            name='welcome_message',
            field=models.TextField(help_text='This text will be sent to new users in your community.'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='EUR. Leave it blank for no price.', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='publicuser',
            name='avatar',
            field=models.ImageField(help_text='Your public image in the community.', upload_to='uploads/avatars/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='request',
            name='reward',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='EUR. Leave it blank for no reward.', max_digits=10, null=True),
        ),
    ]
