# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-04 19:42
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('auzonetweb', '0002_auto_20160502_1053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='access_type',
            field=models.CharField(choices=[('PU', 'Public'), ('PR', 'Private')], default='PU',
                                   help_text='You can protect with password the community access.', max_length=2,
                                   verbose_name='Tipo de acceso'),
        ),
        migrations.AlterField(
            model_name='community',
            name='password',
            field=models.CharField(blank=True, max_length=250, verbose_name='Password'),
        ),
        migrations.AlterField(
            model_name='community',
            name='welcome_message',
            field=models.TextField(help_text='This text will be sent to new users in your community.',
                                   verbose_name='Mensaje de bienvenida'),
        ),
        migrations.AlterField(
            model_name='communitymessage',
            name='message_text',
            field=models.TextField(verbose_name='Texto'),
        ),
        migrations.AlterField(
            model_name='communitymessage',
            name='message_type',
            field=models.CharField(choices=[('I', 'Info'), ('W', 'Warning')], max_length=1,
                                   verbose_name='Message type'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auzonetweb.Category',
                                    verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='community',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auzonetweb.Community',
                                    verbose_name='Community'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='detail',
            field=models.TextField(verbose_name='Detail'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='image',
            field=models.ImageField(blank=True, upload_to='uploads/offers/%Y/%m/%d/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0,
                                      help_text='EUR. Leave it blank for no price.', max_digits=10, null=True,
                                      verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='title',
            field=models.CharField(max_length=250, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='publicuser',
            name='avatar',
            field=models.ImageField(upload_to='uploads/avatars/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='publicuser',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1),
        ),
        migrations.AlterField(
            model_name='request',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auzonetweb.Category',
                                    verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='request',
            name='detail',
            field=models.TextField(verbose_name='Detail'),
        ),
        migrations.AlterField(
            model_name='request',
            name='due_date',
            field=models.DateField(blank=True, null=True, verbose_name='Due date'),
        ),
        migrations.AlterField(
            model_name='request',
            name='image',
            field=models.ImageField(blank=True, upload_to='uploads/requests/%Y/%m/%d/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='request',
            name='reward',
            field=models.DecimalField(blank=True, decimal_places=2, default=0,
                                      help_text='EUR. Leave it blank for no reward.', max_digits=10, null=True,
                                      verbose_name='Reward'),
        ),
        migrations.AlterField(
            model_name='request',
            name='title',
            field=models.CharField(max_length=250, verbose_name='Title'),
        ),
    ]
