# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-24 10:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auzonetweb', '0003_auto_20160219_1111'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='client_voted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='owner_voted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='offer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auzonetweb.Offer'),
        ),
        migrations.AlterField(
            model_name='order',
            name='request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auzonetweb.Request'),
        ),
    ]
