# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-08 11:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auzonetweb', '0004_auto_20160224_1130'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='request',
            new_name='auzonetrequest',
        ),
        migrations.AlterField(
            model_name='offer',
            name='status',
            field=models.CharField(choices=[('A', 'Active'), ('P', 'Pending'), ('F', 'Finished')], default='A', max_length=1),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('A', 'Active'), ('P', 'Pending'), ('F', 'Finished')], default='A', max_length=1),
        ),
        migrations.AlterField(
            model_name='request',
            name='status',
            field=models.CharField(choices=[('A', 'Active'), ('P', 'Pending'), ('F', 'Finished')], default='A', max_length=1),
        ),
    ]
